### ISSUE TITLE
Left Pad Times

### ISSUE THREAD

**Issue by gary-kim** [TheJeterLP/ChatEx#1]
Thank you for this plugin and open sourcing it.

Is there a built in way to left pad the month/hours/minute/seconds with `0` that I'm not finding in the code? I have a patch ready to add that if there isn't a way currently.

**Comment by TheJeterLP** [comment]
What exactly do you mean with left pad? Do you have an example?

Mit freundlichen Grüßen

Joey Peter

Gary Kim <notifications@github.com> schrieb am Di., 3. Dez. 2019, 13:33:

**Comment by gary-kim** [comment]
Instead of showing 1 o'clock as `1`, showing it as `01`.

EDIT: Can I open a PR?
