### ISSUE TITLE
No cross-server-wide messages

### ISSUE THREAD

**Issue by Simul4kruM** [TheJeterLP/ChatEx#116]
I installed chatex on my 4 backend server by following the tasks in the wiki for bungeecord installation. I did set bungeecord: true in config.yml and did restart every server. I am not able to post a message cross-server-wide on any of those 4 servers. If I type p.e. !hello world, this message is showed on my logged server as "!hello world", just as I typed it. Same with region chat. If I type any message like .Hello, it is showed as ".Hello" and not as expected with [world][prefix][player][suffix][message].

The backend servers are running paper 1.19.4, the proxy is running waterfall 1.20. Using ChatEx 3.0.1 in combination with ChatColor2, HexNicks and TAB.

See log and config below... (.yml are not supported, so I changed config-file to .txt)
[2023-06-29-2.log](https://github.com/TheJeterLP/ChatEx/files/11905122/2023-06-29-2.log)
[config.txt](https://github.com/TheJeterLP/ChatEx/files/11905128/config.txt)

**Comment by TheJeterLP** [comment]
I've never heard of waterfall, could you confirm that it works in bungee cord servers?

**Comment by Simul4kruM** [comment]
Waterfall is an upgraded BungeeCord, offering full compatibility with improvements to performance and stability, made by Papermc...

https://papermc.io/software/waterfall

**Comment by TheJeterLP** [comment]
Okay, and how is your permissions setup? Usually with setups like this you use luck perms with a MySQL database, so all the groups, prefixes etc are globally the same

**Comment by TheJeterLP** [comment]
Turns out Chatcolor is the problem and it's not compatible. So try to remove it and report again. Closing for now
