### ISSUE TITLE
[BUG] Ad blocker not working

### ISSUE THREAD

**Issue by lubaskinc0de** [TheJeterLP/ChatEx#117]
**Describe the bug**
my ad blocker is not working, im trying to put ! https://hui.com/ in chat and it success paste in the chat

**To Reproduce**
Steps to reproduce the behavior: simple paste ! https://hui.com/ to chat

**Expected behavior**
this message is blocked

**Screenshots**
![2023-07-02_20 20 17](https://github.com/TheJeterLP/ChatEx/assets/100635212/4be6872a-2e89-41eb-b7e0-526c8cb371d3)

**Please complete the following information:**

- OS: Windows
- Java Version 19
- Minecraft Version 1.20,1
- ChatEx Version 2.6.0

**Files (please complete the following information):**

- Link to Server Startup Log file: 
- Link to ChatEx Configuration file: https://linkode.org/#soYd0nP7Wq32uaUpoWbJ76

**Additional context**

**Comment by TheJeterLP** [comment]
Update chatex First of all. If issue persists reopen issue.

**Comment by TheJeterLP** [comment]
I cannot confirm that, I just tested it. Please assure that your players do NOT have the chatex.bypassads permission
