### ISSUE TITLE
 [request]

### ISSUE THREAD

**Issue by Spartan302** [TheJeterLP/ChatEx#123]
Make support for tootiple so that you can create tootiple prefixes and also let messages themselves when they were sent! Or players that when you click on the nickname, some kind of command or something else was displayed

**Comment by TheJeterLP** [comment]
I really don't understand what you want here

**Comment by Spartan302** [comment]
when you hover over the player's nickname with the mouse, a hint pops up in the form of text and so that you can attach some text there!

**Comment by TheJeterLP** [comment]
> when you hover over the player's nickname with the mouse, a hint pops up in the form of text and so that you can attach some text there!
> 

Not planned for chatex and doesn't make sense for a chat plugin

**Comment by Spartan302** [comment]
It has because it is part of the chat where you can insert different %plaseholders% depending on when the message was sent or how much the player has played

**Comment by Spartan302** [comment]
There is no third party plugin that adds this, because all chat plugins have it

**Comment by TheJeterLP** [comment]
I won't add that to chatex, out of spec
