### ISSUE TITLE
[BUG DISCORD SRV]

### ISSUE THREAD

**Issue by Spartan302** [TheJeterLP/ChatEx#126]
**Describe the bug**

When writing to a local chat, messages are delivered to discordsrv, this is due to the %messange% placeholder, maybe you don’t have messages separated into global and local because when writing to a local chat, it is still sent to discordsrv with other plugins I didn’t observe this

**Comment by TheJeterLP** [comment]
I don't really understand the problem, maybe you can send some screenshots for explanation?
