### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by 1337Pixelmal** [TheJeterLP/ChatEx#134]
Hello. 
Nice plugin, i also appreciate cross-server feature. But can you make ability to disable ranged mode, so players can write their cross-server messages without ranged prefix '!'?
At first, i thought, that cross-server feature is not working, and after all i tried ranged prefix and so messages started displaying on other servers in my network.

**Comment by 1337Pixelmal** [comment]
Also, i already disabled ranged mode, but still players needs to write ranged prefix to send message across servers.

**Comment by TheJeterLP** [comment]
Hello, yes I can do that with a configuration setting. Will be added for the next release :)
