### ISSUE TITLE
ChatEx error with BetterNick plugin

### ISSUE THREAD

**Issue by eric2788** [TheJeterLP/ChatEx#14]
it caused error when nicked with betternick
https://gyazo.com/c54d81a877efcce929adfded5db26e25.png
my chatex plugin is v1.6, running paperspigot 1.11.2
betternick plugin : https://www.spigotmc.org/resources/better-nick-api-1-8-3-1-11-2.39633/
i have asked plugin author and he told me i should report it to chatex author
my plugin list : https://proxy.spigotmc.org/aea807781fd1328c9c1ee6a29268cc0126432cb7?url=https%3A%2F%2Fgyazo.com%2Fabc0aa3754354bf4c5590b8bee15901d.png

**Comment by TheJeterLP** [comment]
I will take a look into it, thanks for reporting :)
