### ISSUE TITLE
[BUG] BlockedWord list ultra sensitive

### ISSUE THREAD

**Issue by fatmagic** [TheJeterLP/ChatEx#141]
**Describe the bug**
I have a large BlockedWord list, and it's hyper sensitive to partial words (which is OK I guess). Such as when someone types "lava" it was blocking them due to the word "va" being blocked. I had to remove "va" to allow "lava" to be typed.

Currently the word I can't seem to fix is "who". No one can type "who" some reason, even though it's even on the list as a partial (I removed "whore" and it's variations, and it's still blocking it).

Can we get some sort of verbose error-trapping in the console so I know what word it's being caught/matched on? I could then remove or adjust the offending word. I don't know what words to remove to make this work properly, as any word with "who" has been removed from the list.

Thank you.

**Comment by TheJeterLP** [comment]
Hello, I will take a look into that tomorrow! Thanks for reporting! May you send me your ChatEx config.yml file?

**Comment by fatmagic** [comment]
For sure - let me finish cleaning it up (I found some duplicate words). Then testing it one more time, and will send you the YML this afternoon.

**Comment by fatmagic** [comment]
Jeter - here is the (attached as ZIP because GitHub doesn't allow YML)
[config.zip](https://github.com/TheJeterLP/ChatEx/files/13945147/config.zip)

With this config, I still can't say the word "who" - it says it's blocked. But I don't have any words with "who" on the list.
If I remove all the BlockedWords entirely, then I can say "who" again - but of course, no bad words are blocked!
Very strange.

Appreciate your help on this!

EDIT: So you know, I'm running this on the latest version of Spigot on Java v17.

**Comment by TheJeterLP** [comment]
Thanks for sending, I think this is the longest list I've ever seen xD I will try it out later today

**Comment by TheJeterLP** [comment]
Fixed by #142, is released in v3.2.1.
Seeing which word blocks the message can be seen by setting debug=true in chatex config file :)

**Comment by fatmagic** [comment]
OK Jeter - I will try this out and let you know!
Thanks for adding that in so I can see what is going on.

**Comment by fatmagic** [comment]
@Jeter - so the debug works great, thank you. But now the words are absolutely case-sensitive. Which is very bad. 

Example... on my list is "Anus". Now it will ONLY filter "Anus" with a capital "A" and lowercase "nus". If I type "AnUs" it allows it. If I type "anus" it allows it.

I would have to make the word match list insanely long to account for every possible variation of spelling with lowercase and uppercase interchanging! 

Sorry for the bad news :( I am reverting to 3.2.0 so people can't get around the filter as easily.

See log examples below:

![image](https://github.com/TheJeterLP/ChatEx/assets/20613563/08340f39-3225-4cd9-87ed-c820ef8dcf54)

**Comment by TheJeterLP** [comment]
Oh my bad, I'll fix that later that day or tomorrow

mit freundlichen Grüßen
Joey Peter

fatmagic ***@***.***> schrieb am Di., 16. Jan. 2024, 16:42:

**Comment by fatmagic** [comment]
Hey Jeter - any luck on finding a way to fix this? Don't mean to rush you - my players are upset about the blocked standard words (about 12 common words blocked we've found - LOL). Would love to debug these today :) :)

**Comment by TheJeterLP** [comment]
Not yet, I'm still at work. Will do when I get at home.

**Comment by TheJeterLP** [comment]
v3.2.2 is building right now, you can download it from github when ready and test with that. Please tell me if everythings fine

**Comment by TheJeterLP** [comment]
Damn it can't build because purpur repo is offline, can you please contact me on the discord server so I can send you the new build?

**Comment by fatmagic** [comment]
Jeter what is your Discord?

**Comment by fatmagic** [comment]
Just adding final comment that this fixed my issue, and is working great now!
