### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by WataLaker37821** [TheJeterLP/ChatEx#159]
Hi, i wanted to ask for DiscordSRV support, could you please add it?

It will allow choose which chat channel will be broadcasted in Discord channel, so local chat won't be seen

**Comment by TheJeterLP** [comment]
Hi, I just tried it out and DiscordSRV provides NO documentation for their API and I just don't have time to look at how other Plugins do it or keep it working and maintained, therefore I will NOT add DiscordSRV support.
