### ISSUE TITLE
Custom Join and Leave Messages

### ISSUE THREAD

**Issue by gary-kim** [TheJeterLP/ChatEx#20]
The idea would be to have a config for custom join and leave messages.

I currently have a version for my own server an I'd like to upstream it.

**Comment by TheJeterLP** [comment]
There is a config in your locales file

Mit freundlichen Grüßen
Joey Peter

Gary Kim <notifications@github.com> schrieb am Mi., 3. Juni 2020, 13:59:

**Comment by gary-kim** [comment]
Yep, got pointed there by the Discord. I'll close this. Sorry.

**Comment by gary-kim** [comment]
Is there a central place for documentation at the moment?
