### ISSUE TITLE
Updater no longer works

### ISSUE THREAD

**Issue by theTreeSerok** [TheJeterLP/ChatEx#22]
Updater tries to find a resource that doesn't exist.

From what I can tell, it's trying to look here: https://api.curseforge.com/servermods/filesrojectIds=65863 where there is nothing.

Spits out a bunch of errors into the console, but is otherwise harmless (aside from auto-updating, I presume, but this plugin hasn't received an update in quite some time).

**Comment by Versaucey** [comment]
have you found a solution yet? (i know it's been 8 months)
