### ISSUE TITLE
Server Freeze if struggling to find update service

### ISSUE THREAD

**Issue by MissPotato** [TheJeterLP/ChatEx#24]
This happened when the server was unable to contact the Mojang authentication servers, leading Paper Devs to believe it might be related to the generic DDOS going on right now. They did say, however, the async is causing the mainthread to freeze when waiting on a response.

Linked below is the log: 

https://pastebin.com/833uYnGW

**Comment by TheJeterLP** [comment]
Do you have any idea on how to reproduce this?

MissPotato <notifications@github.com> schrieb am Mi., 17. Juni 2020, 21:15:

**Comment by MissPotato** [comment]
Unfortunately no, it has only happened when the update server new it was connected to the internet but couldn't actually make a connection. Maybe starting a local server with internet connection and then disabling the internet connection might work?

**Comment by TheJeterLP** [comment]
Disabling the connection didnt work unfortunately
