### ISSUE TITLE
Nick parse error

### ISSUE THREAD

**Issue by JimusHimus** [TheJeterLP/ChatEx#25]
When I set special nickname such as "%s%n%x" chatex handles it wrongly.

![изображение](https://user-images.githubusercontent.com/39002687/86161794-74b64b80-bb16-11ea-8ff0-502d496a2e85.png)
"seconds" ![изображение](https://user-images.githubusercontent.com/39002687/86161852-90b9ed00-bb16-11ea-9e81-3f0e92553588.png)
![изображение](https://user-images.githubusercontent.com/39002687/86161895-a3342680-bb16-11ea-8c69-8817c02b436a.png)

**Comment by TheJeterLP** [comment]
Fixed by latest commit :)
