### ISSUE TITLE
Will ChatEx be compatible with the PEX 2.0 Snapshot's?

### ISSUE THREAD

**Issue by csBlackWolf** [TheJeterLP/ChatEx#5]
I am testing the PermissionEX 2.0 Snapshot on my server and try to use it with ChatEx.
But it looks like it is not compatible with the build i am using.

Will it be compatible in the future?

The Snapshots can be found here:
https://jenkins.addstar.com.au/job/PermissionsEx/lastSuccessfulBuild/

**Comment by TheJeterLP** [comment]
As long as pex 2.0 will be compatible with vault, ChatEx will be compatible too

**Comment by csBlackWolf** [comment]
If i try to load it with ChatEX i get a error:

> [18:38:09] [Server thread/INFO]: [PermissionsEx] Loading PermissionsEx v2.0-SNAPSHOT-b33Addstar
> [18:38:12] [Server thread/INFO]: [PermissionsEx] Enabling PermissionsEx v2.0-SNAPSHOT-b33Addstar
> [18:38:14] [Server thread/INFO]: [PermissionsEx] Successfully registered WorldGuard region context
> [18:38:14] [Server thread/INFO]: [PermissionsEx] Successfully registered Vault's Permission and Chat interfaces
> [18:38:44] [Server thread/INFO]: [ChatEx] Enabling ChatEx v2.4.1
> [18:38:44] [Server thread/ERROR]: Error occurred while enabling ChatEx v2.4.1 (Is it up to date?)
> java.lang.NoClassDefFoundError: ru/tehkode/permissions/bukkit/PermissionsEx
> 	at de.thejeterlp.chatex.plugins.PermissionsEx.getName(PermissionsEx.java:82) ~[?:?]
> 	at de.thejeterlp.chatex.plugins.PluginManager.load(PluginManager.java:30) ~[?:?]
> 	at de.thejeterlp.chatex.ChatEX.onEnable(ChatEX.java:24) ~[?:?]
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
> 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
> 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) [minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
> 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
> 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
> 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
> 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274) [minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
> 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
> Caused by: java.lang.ClassNotFoundException: ru.tehkode.permissions.bukkit.PermissionsEx
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_232]
> 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
> 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
> 	... 12 more

I downloaded the latest build from https://dev.bukkit.org/projects/chatex
Did i miss something?

**Comment by TheJeterLP** [comment]
Download the latest build from spigotmc. There is a link on the bukkitdev page. I removed hooking directly to pex1 because of this

**Comment by csBlackWolf** [comment]
Sorry, my fault. I didn't read the information on the Bukkit page. xP

I used the latest build from SpigotMC now and it looked good at first,. But after connecting to the server, I got a new error.

> [23:00:08] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to ChatEx v2.4.3
> org.bukkit.event.EventException: null
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
>         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) [minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) [minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
>         at net.minecraft.server.v1_15_R1.PlayerList.a(PlayerList.java:176) [minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
>         at net.minecraft.server.v1_15_R1.LoginListener.c(LoginListener.java:154) [minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
>         at net.minecraft.server.v1_15_R1.LoginListener.tick(LoginListener.java:53) [minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
>         at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:220) [minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
>         at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:129) [minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
>         at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1105) [minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
>         at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
>         at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
>         at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
> Caused by: java.lang.NullPointerException
>         at java.lang.String.replace(String.java:2240) ~[?:1.8.0_232]
>         at de.jeter.chatex.utils.Utils.replacePlayerPlaceholders(Utils.java:59) ~[?:?]
>         at de.jeter.chatex.PlayerListener.onJoin(PlayerListener.java:32) ~[?:?]
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
>         at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
>         ... 13 more
> [23:00:09] [Server thread/INFO]: csBlackWolf[/79.205.189.208:63744] logged in with entity id 163 at ([lobby]1.4839644706554327, 50.0, -0.582576728585459)
> [23:00:15] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 6009ms or 120 ticks behind
> [23:00:17] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to ChatEx v2.4.3
> org.bukkit.event.EventException: null
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
>         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) [minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) [minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
>         at net.minecraft.server.v1_15_R1.PlayerConnection.chat(PlayerConnection.java:1580) [minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
>         at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1518) [minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
>         at net.minecraft.server.v1_15_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) [minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_232]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_232]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
> Caused by: java.lang.NullPointerException
>         at java.lang.String.replace(String.java:2240) ~[?:1.8.0_232]
>         at de.jeter.chatex.utils.Utils.replacePlayerPlaceholders(Utils.java:59) ~[?:?]
>         at de.jeter.chatex.ChatListener.onChat(ChatListener.java:87) ~[?:?]
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
>         at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[minecraft_server.jar:git-Spigot-a03b1fd-bbe3d58]
>         ... 11 more
> 

Any ideas?

**Comment by TheJeterLP** [comment]
I have to look into that later tomorrow

Mit freundlichen Grüßen

Joey Peter

csBlackWolf <notifications@github.com> schrieb am Mo., 13. Apr. 2020, 01:09:

**Comment by csBlackWolf** [comment]
OK. Thank you for your time and work. ^^

**Comment by TheJeterLP** [comment]
should be fixed with the latest build
