### ISSUE TITLE
[BUG] ConcurrentModificationException

### ISSUE THREAD

**Issue by Serega007RU** [TheJeterLP/ChatEx#67]
**Describe the bug**
Sometimes with some chance when you write to the chat it gives an error in the console and does not send a message to the chat

**To Reproduce**
1. Write to the chat
2. With some chance there will be errors in the console

**Expected behavior**
There should be no error in the console and the message should be sent to the chat

**Screenshots**
![image](https://user-images.githubusercontent.com/64780091/187052160-4eb06f0a-3c2e-44fc-b74b-9200759d5df1.png)

**Please complete the following information:**
 - OS: Ubuntu
 - Java Version 1.8
 - Minecraft Version 1.7.10
 - ChatEx Version 2.8.3

**Files (please complete the following information):**
 - Link to Server Startup Log file: [2022-08-27-5.log](https://github.com/TheJeterLP/ChatEx/files/9438852/2022-08-27-5.log)
 - Link to ChatEx Configuration file: [config.yml.txt](https://github.com/TheJeterLP/ChatEx/files/9438851/config.yml.txt)

**Additional context**
Not required, see logs

**Comment by TheJeterLP** [comment]
Update to newer Minecraft version.

**Comment by Serega007RU** [comment]
You 're on spigotmc.org indicated that you support 1.7.10, then in that case, remove it and do not deceive people

**Comment by TheJeterLP** [comment]
> You 're on spigotmc.org indicated that you support 1.7.10, then in that case, remove it and do not deceive people

Done.
