### ISSUE TITLE
[BUG] message-format and global-message-format are not set's the format of the chat.

### ISSUE THREAD

**Issue by YeahAntiSkiddedAdmin** [TheJeterLP/ChatEx#69]
**Describe the bug**
ChatEx can't set global message format and message format.

**Expected behavior**
ChatEx will set global message format and message format to what i wanted.

**Screenshots**
![image](https://user-images.githubusercontent.com/100999789/193199564-6a6c281e-2d5f-4c2d-836f-5dd1060402bd.png)
![image](https://user-images.githubusercontent.com/100999789/193199583-a0a56a99-f2d4-4e1d-a34a-99db44b37c71.png)

**Please complete the following information:**
 - Java Version: 16
 - Minecraft Version: 1.17.1
 - ChatEx Version: 2.6.1

**Files (please complete the following information):**
 - Link to Server Startup Log file: https://mclo.gs/ukjnZbW
 - Link to ChatEx Configuration file: https://pastebin.com/raw/bMXSHp0x

**Comment by TheJeterLP** [comment]
Update to 2.8.5

**Comment by TheJeterLP** [comment]
![Screenshot 2022-10-02 150129](https://user-images.githubusercontent.com/3790121/193456001-3815ff34-1258-41d9-8c2d-6dc211b38066.png)
