### ISSUE TITLE
Persisting "New update" msg on latest version

### ISSUE THREAD

**Issue by Picajoluna** [TheJeterLP/ChatEx#7]
Hello,

I tried both downloading the jar from the Bukkit website, and cloning this repo / mvn clean install to generate a jar -- and in both cases, I got this message:
```
[12:03:52 INFO]: [ChatEx] Update found!
```

and in-game:
![outdated](https://i.imgur.com/uBpp37f.png)

Just seems you need to update what's considered the latest version (or am I accidentally using an unstable build?).

Danke!

**Comment by TheJeterLP** [comment]
No that's correct, the problem is that the spigot API where the updater
fetches the last update does not update very often, that's why it's very
unstable

Pica <notifications@github.com> schrieb am Mo., 20. Apr. 2020, 14:08:

**Comment by Picajoluna** [comment]
Oh okay no worries then.
Sweet job with the plugin btw! Simple enough it does the job, yet has the features I want/need (prefixes in chat & tab).
