### ISSUE TITLE
Configure loading error

### ISSUE THREAD

**Issue by archroot** [TheJeterLP/ChatEx#76]
The plugin won't start deleting the folder with the configs doesn't help

![изображение](https://user-images.githubusercontent.com/41123605/193475142-6a3a3fce-0dd7-4e23-b454-135ac71698f1.png)

Log:  https://pastebin.com/YbVNmPMs

**Comment by TheJeterLP** [comment]
What server version are you using?

**Comment by TheJeterLP** [comment]
Seems to be an old one.

**Comment by archroot** [comment]
PaperSpigot 1.16.5
ChatEx v2.8.7

**Comment by archroot** [comment]
> What server version are you using?

PaperSpigot 1.16.5
ChatEx v2.8.7

https://pastebin.com/RjxxkUuh

**Comment by TheJeterLP** [comment]
I'll have a look into that tomorrow.

**Comment by TheJeterLP** [comment]
Fixed in 2.8.9
