### ISSUE TITLE
Глобальный & Локальный

### ISSUE THREAD

**Issue by MCDunknown** [TheJeterLP/ChatEx#81]
**Global chat** and sometimes **local** chat is not available after reloading the module (Plugin) via the /chatex reload command, but if you restart the machine via /restart and/or /reload, you can confirm the ability to write to the global chat remains.

**UPD:** _If the user re-connects to the game, the error remains._
**UPD:** _When trying to write something, an error is generated related to the Anti-spam module._
**UPD:** _Plugin version: **2.9.0**_

![image](https://user-images.githubusercontent.com/115187307/194405322-0ff04cdf-29fb-4181-aeec-b0bdf2e14806.png)

**UPD:** _After restarting the server_
![image](https://user-images.githubusercontent.com/115187307/194406910-b17deef4-2be0-4d50-b00f-4d869b032f8d.png)

**Comment by TheJeterLP** [comment]
Please use the bug report template next time.

**Comment by TheJeterLP** [comment]
Fixed in 2.9.1
