### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by roggy666** [TheJeterLP/ChatEx#83]
1. Add support for hex placeholders
2. Please, add placeholder for local and global chat (So that you can put it in other chat-related plugins)
For example %chat-type%

**Comment by roggy666** [comment]
thanks in advance

**Comment by roggy666** [comment]
I add support for hex placeholders! I will be very happy if you add this in an update! https://mega.nz/file/W0FH2K4A#tiZ73D2vpH7te2dbahupg4-xg9buB52ddd3tVjvWlV8

**Comment by roggy666** [comment]
Check ChatListener.java and Utils.java

**Comment by TheJeterLP** [comment]
Create a PR in GitHub.
