### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nvchks** [TheJeterLP/ChatEx#98]
- OS: Ubuntu (Java 18)
- Minecraft Version [1.19.2]
- ChatEx Version [3.0.1]

**Files**

- Link to Server Startup Log file:
- Link to ChatEx Configuration file:

**Additional context**
Greetings. Faced with the problem of incorrect configuration of the plugin. When specifying parameters &#FFFF00&l[L] %prefix %displayname %uclans_tag_formated%%suffix: A space appears after %displayname.

**Comment by nvchks** [comment]
Added the required files.
[latest.log](https://github.com/TheJeterLP/ChatEx/files/10418908/latest.log)
[config.log](https://github.com/TheJeterLP/ChatEx/files/10418918/config.log)


The ChatEx configuration file was added in .log format, please change the file format for viewing.

**Comment by TheJeterLP** [comment]
So just that I understand correctly, the issue is just about the space added?

**Comment by TheJeterLP** [comment]
- You have configured: 
message-format: '&#FFFF00&l[L] %prefix %displayname %uclans_tag_formated%%suffix:
  %message'

Remove the space after the %displayname.

**Comment by Hawash1** [comment]
I mean the message when the player enters the server for the first time. For example: firstmsg: '&c[►]&b&lPlayer &e&l{PLAYER} &b&lLogged into the server for the first time. &a&lWe wish him good luck!'
